var windowWidth = $(window).width();
var windowSm = 768;
if (windowWidth <= windowSm) {
	particlesJS("particles-js", {
		"particles":{
			"number":{
				"value":6,//この数値を変更すると桜の数が増減できる
				"density":{
					"enable":true,
					"value_area":1000
				}
			},
			"color":{
				"value":"#fff"
			},
			"shape":{
				"type":"image",//形状は画像を指定
				"stroke":{
					"width":0,
				},
				"image":{
					"src":"png/heartA.png",//【重要】画像を指定！桜の画像を設定してください。
					"width":100,
					"height":120
				}
			},
			"opacity":{
				"value":0.06409588744762158,
				"random":true,
				"anim":{
					"enable":false,
					"speed":1,
					"opacity_min":0.1,
					"sync":false
				}
			},
			"size":{
				"value":50,
				"random":true,//サイズをランダムに
				"anim":{
					"enable":true,
					"speed":4,
					"size_min":25,
					"sync":false
				}
			},
			"line_linked":{
				"enable":false,
			},
			"move":{
				"enable":true,
				"speed":7,//この数値を小さくするとゆっくりな動きになる
				"direction":"bottom-right",//右下に向かって落ちる
				"random":false,//動きはランダムにしない
				"straight":false,//動きをとどめない
				"out_mode":"out",//画面の外に出るように描写
				"bounce":false,//跳ね返りなし
				"attract":{
					"enable":false,
					"rotateX":281.9177489524316,
					"rotateY":127.670995809726
				}
			}
		},
		"interactivity":{
			"detect_on":"canvas",
			"events":{
				"onhover":{
					"enable":false,
				},
				"onclick":{
					"enable":false,
				},
				"resize":true
			}
		},
		"retina_detect":true,
		"resize":true
	});

  particlesJS("particles-js-2", {
		"particles":{
			"number":{
				"value":6,//この数値を変更すると桜の数が増減できる
				"density":{
					"enable":true,
					"value_area":1000
				}
			},
			"color":{
				"value":"#fff"
			},
			"shape":{
				"type":"image",//形状は画像を指定
				"stroke":{
					"width":0,
				},
				"image":{
					"src":"png/spadeA.png",//【重要】画像を指定！桜の画像を設定してください。
					"width":100,
					"height":120
				}
			},
			"opacity":{
				"value":0.06409588744762158,
				"random":true,
				"anim":{
					"enable":false,
					"speed":1,
					"opacity_min":0.1,
					"sync":false
				}
			},
			"size":{
				"value":50,
				"random":true,//サイズをランダムに
				"anim":{
					"enable":true,
					"speed":4,
					"size_min":25,
					"sync":false
				}
			},
			"line_linked":{
				"enable":false,
			},
			"move":{
				"enable":true,
				"speed":7,//この数値を小さくするとゆっくりな動きになる
				"direction":"bottom",//右下に向かって落ちる
				"random":false,//動きはランダムにしない
				"straight":false,//動きをとどめない
				"out_mode":"out",//画面の外に出るように描写
				"bounce":false,//跳ね返りなし
				"attract":{
					"enable":false,
					"rotateX":281.9177489524316,
					"rotateY":127.670995809726
				}
			}
		},
		"interactivity":{
			"detect_on":"canvas",
			"events":{
				"onhover":{
					"enable":false,
				},
				"onclick":{
					"enable":false,
				},
				"resize":true
			}
		},
		"retina_detect":true,
		"resize":true
	});

	particlesJS("particles-js-3", {
		"particles":{
			"number":{
				"value":6,//この数値を変更すると桜の数が増減できる
				"density":{
					"enable":true,
					"value_area":1000
				}
			},
			"color":{
				"value":"#fff"
			},
			"shape":{
				"type":"image",//形状は画像を指定
				"stroke":{
					"width":0,
				},
				"image":{
					"src":"png/King.png",//【重要】画像を指定！桜の画像を設定してください。
					"width":220,
					"height":220
				}
			},
			"opacity":{
				"value":0.06409588744762158,
				"random":true,
				"anim":{
					"enable":false,
					"speed":1,
					"opacity_min":0.1,
					"sync":false
				}
			},
			"size":{
				"value":90,
				"random":true,//サイズをランダムに
				"anim":{
					"enable":true,
					"speed":4,
					"size_min":40,
					"sync":false
				}
			},
			"line_linked":{
				"enable":false,
			},
			"move":{
				"enable":true,
				"speed":7,//この数値を小さくするとゆっくりな動きになる
				"direction":"bottom",//右下に向かって落ちる
				"random":false,//動きはランダムにしない
				"straight":false,//動きをとどめない
				"out_mode":"out",//画面の外に出るように描写
				"bounce":false,//跳ね返りなし
				"attract":{
					"enable":false,
					"rotateX":281.9177489524316,
					"rotateY":127.670995809726
				}
			}
		},
		"interactivity":{
			"detect_on":"canvas",
			"events":{
				"onhover":{
					"enable":false,
				},
				"onclick":{
					"enable":false,
				},
				"resize":true
			}
		},
		"retina_detect":true,
		"resize":true
	});

	particlesJS("particles-js-4", {
		"particles":{
			"number":{
				"value":6,//この数値を変更すると桜の数が増減できる
				"density":{
					"enable":true,
					"value_area":1000
				}
			},
			"color":{
				"value":"#fff"
			},
			"shape":{
				"type":"image",//形状は画像を指定
				"stroke":{
					"width":0,
				},
				"image":{
					"src":"png/joker.png",//【重要】画像を指定！桜の画像を設定してください。
					"width":210,
					"height":240
				}
			},
			"opacity":{
				"value":0.06409588744762158,
				"random":true,
				"anim":{
					"enable":false,
					"speed":1,
					"opacity_min":0.1,
					"sync":false
				}
			},
			"size":{
				"value":60,
				"random":true,//サイズをランダムに
				"anim":{
					"enable":true,
					"speed":4,
					"size_min":30,
					"sync":false
				}
			},
			"line_linked":{
				"enable":false,
			},
			"move":{
				"enable":true,
				"speed":7,//この数値を小さくするとゆっくりな動きになる
				"direction":"bottom",//右下に向かって落ちる
				"random":false,//動きはランダムにしない
				"straight":false,//動きをとどめない
				"out_mode":"out",//画面の外に出るように描写
				"bounce":false,//跳ね返りなし
				"attract":{
					"enable":false,
					"rotateX":281.9177489524316,
					"rotateY":127.670995809726
				}
			}
		},
		"interactivity":{
			"detect_on":"canvas",
			"events":{
				"onhover":{
					"enable":false,
				},
				"onclick":{
					"enable":false,
				},
				"resize":true
			}
		},
		"retina_detect":true,
		"resize":true
	});

	particlesJS("particles-js-5", {
		"particles":{
			"number":{
				"value":6,//この数値を変更すると桜の数が増減できる
				"density":{
					"enable":true,
					"value_area":1000
				}
			},
			"color":{
				"value":"#fff"
			},
			"shape":{
				"type":"image",//形状は画像を指定
				"stroke":{
					"width":0,
				},
				"image":{
					"src":"png/queen.png",//【重要】画像を指定！桜の画像を設定してください。
					"width":210,
					"height":240
				}
			},
			"opacity":{
				"value":0.06409588744762158,
				"random":true,
				"anim":{
					"enable":false,
					"speed":1,
					"opacity_min":0.1,
					"sync":false
				}
			},
			"size":{
				"value":60,
				"random":true,//サイズをランダムに
				"anim":{
					"enable":true,
					"speed":4,
					"size_min":30,
					"sync":false
				}
			},
			"line_linked":{
				"enable":false,
			},
			"move":{
				"enable":true,
				"speed":7,//この数値を小さくするとゆっくりな動きになる
				"direction":"bottom",//右下に向かって落ちる
				"random":false,//動きはランダムにしない
				"straight":false,//動きをとどめない
				"out_mode":"out",//画面の外に出るように描写
				"bounce":false,//跳ね返りなし
				"attract":{
					"enable":false,
					"rotateX":281.9177489524316,
					"rotateY":127.670995809726
				}
			}
		},
		"interactivity":{
			"detect_on":"canvas",
			"events":{
				"onhover":{
					"enable":false,
				},
				"onclick":{
					"enable":false,
				},
				"resize":true
			}
		},
		"retina_detect":true,
		"resize":true
	});
} else {
	particlesJS("particles-js", {
		"particles":{
			"number":{
				"value":2,//この数値を変更すると桜の数が増減できる
				"density":{
					"enable":true,
					"value_area":1000
				}
			},
			"color":{
				"value":"#fff"
			},
			"shape":{
				"type":"image",//形状は画像を指定
				"stroke":{
					"width":0,
				},
				"image":{
					"src":"png/heartA.png",//【重要】画像を指定！桜の画像を設定してください。
					"width":100,
					"height":120
				}
			},
			"opacity":{
				"value":0.06409588744762158,
				"random":true,
				"anim":{
					"enable":false,
					"speed":1,
					"opacity_min":0.1,
					"sync":false
				}
			},
			"size":{
				"value":90,
				"random":true,//サイズをランダムに
				"anim":{
					"enable":true,
					"speed":4,
					"size_min":55,
					"sync":false
				}
			},
			"line_linked":{
				"enable":false,
			},
			"move":{
				"enable":true,
				"speed":7,//この数値を小さくするとゆっくりな動きになる
				"direction":"bottom-right",//右下に向かって落ちる
				"random":false,//動きはランダムにしない
				"straight":false,//動きをとどめない
				"out_mode":"out",//画面の外に出るように描写
				"bounce":false,//跳ね返りなし
				"attract":{
					"enable":false,
					"rotateX":281.9177489524316,
					"rotateY":127.670995809726
				}
			}
		},
		"interactivity":{
			"detect_on":"canvas",
			"events":{
				"onhover":{
					"enable":false,
				},
				"onclick":{
					"enable":false,
				},
				"resize":true
			}
		},
		"retina_detect":true,
		"resize":true
	});

  particlesJS("particles-js-2", {
		"particles":{
			"number":{
				"value":2,//この数値を変更すると桜の数が増減できる
				"density":{
					"enable":true,
					"value_area":1000
				}
			},
			"color":{
				"value":"#fff"
			},
			"shape":{
				"type":"image",//形状は画像を指定
				"stroke":{
					"width":0,
				},
				"image":{
					"src":"png/spadeA.png",//【重要】画像を指定！桜の画像を設定してください。
					"width":100,
					"height":120
				}
			},
			"opacity":{
				"value":0.06409588744762158,
				"random":true,
				"anim":{
					"enable":false,
					"speed":1,
					"opacity_min":0.1,
					"sync":false
				}
			},
			"size":{
				"value":90,
				"random":true,//サイズをランダムに
				"anim":{
					"enable":true,
					"speed":4,
					"size_min":55,
					"sync":false
				}
			},
			"line_linked":{
				"enable":false,
			},
			"move":{
				"enable":true,
				"speed":7,//この数値を小さくするとゆっくりな動きになる
				"direction":"bottom",//右下に向かって落ちる
				"random":false,//動きはランダムにしない
				"straight":false,//動きをとどめない
				"out_mode":"out",//画面の外に出るように描写
				"bounce":false,//跳ね返りなし
				"attract":{
					"enable":false,
					"rotateX":281.9177489524316,
					"rotateY":127.670995809726
				}
			}
		},
		"interactivity":{
			"detect_on":"canvas",
			"events":{
				"onhover":{
					"enable":false,
				},
				"onclick":{
					"enable":false,
				},
				"resize":true
			}
		},
		"retina_detect":true,
		"resize":true
	});

	particlesJS("particles-js-3", {
		"particles":{
			"number":{
				"value":2,//この数値を変更すると桜の数が増減できる
				"density":{
					"enable":true,
					"value_area":1000
				}
			},
			"color":{
				"value":"#fff"
			},
			"shape":{
				"type":"image",//形状は画像を指定
				"stroke":{
					"width":0,
				},
				"image":{
					"src":"png/King.png",//【重要】画像を指定！桜の画像を設定してください。
					"width":220,
					"height":220
				}
			},
			"opacity":{
				"value":0.06409588744762158,
				"random":true,
				"anim":{
					"enable":false,
					"speed":1,
					"opacity_min":0.1,
					"sync":false
				}
			},
			"size":{
				"value":180,
				"random":true,//サイズをランダムに
				"anim":{
					"enable":true,
					"speed":4,
					"size_min":90,
					"sync":false
				}
			},
			"line_linked":{
				"enable":false,
			},
			"move":{
				"enable":true,
				"speed":7,//この数値を小さくするとゆっくりな動きになる
				"direction":"bottom",//右下に向かって落ちる
				"random":false,//動きはランダムにしない
				"straight":false,//動きをとどめない
				"out_mode":"out",//画面の外に出るように描写
				"bounce":false,//跳ね返りなし
				"attract":{
					"enable":false,
					"rotateX":281.9177489524316,
					"rotateY":127.670995809726
				}
			}
		},
		"interactivity":{
			"detect_on":"canvas",
			"events":{
				"onhover":{
					"enable":false,
				},
				"onclick":{
					"enable":false,
				},
				"resize":true
			}
		},
		"retina_detect":true,
		"resize":true
	});

	particlesJS("particles-js-4", {
		"particles":{
			"number":{
				"value":2,//この数値を変更すると桜の数が増減できる
				"density":{
					"enable":true,
					"value_area":1000
				}
			},
			"color":{
				"value":"#fff"
			},
			"shape":{
				"type":"image",//形状は画像を指定
				"stroke":{
					"width":0,
				},
				"image":{
					"src":"png/joker.png",//【重要】画像を指定！桜の画像を設定してください。
					"width":210,
					"height":240
				}
			},
			"opacity":{
				"value":0.06409588744762158,
				"random":true,
				"anim":{
					"enable":false,
					"speed":1,
					"opacity_min":0.1,
					"sync":false
				}
			},
			"size":{
				"value":130,
				"random":true,//サイズをランダムに
				"anim":{
					"enable":true,
					"speed":4,
					"size_min":70,
					"sync":false
				}
			},
			"line_linked":{
				"enable":false,
			},
			"move":{
				"enable":true,
				"speed":7,//この数値を小さくするとゆっくりな動きになる
				"direction":"bottom",//右下に向かって落ちる
				"random":false,//動きはランダムにしない
				"straight":false,//動きをとどめない
				"out_mode":"out",//画面の外に出るように描写
				"bounce":false,//跳ね返りなし
				"attract":{
					"enable":false,
					"rotateX":281.9177489524316,
					"rotateY":127.670995809726
				}
			}
		},
		"interactivity":{
			"detect_on":"canvas",
			"events":{
				"onhover":{
					"enable":false,
				},
				"onclick":{
					"enable":false,
				},
				"resize":true
			}
		},
		"retina_detect":true,
		"resize":true
	});

	particlesJS("particles-js-5", {
		"particles":{
			"number":{
				"value":2,//この数値を変更すると桜の数が増減できる
				"density":{
					"enable":true,
					"value_area":1000
				}
			},
			"color":{
				"value":"#fff"
			},
			"shape":{
				"type":"image",//形状は画像を指定
				"stroke":{
					"width":0,
				},
				"image":{
					"src":"png/queen.png",//【重要】画像を指定！桜の画像を設定してください。
					"width":210,
					"height":240
				}
			},
			"opacity":{
				"value":0.06409588744762158,
				"random":true,
				"anim":{
					"enable":false,
					"speed":1,
					"opacity_min":0.1,
					"sync":false
				}
			},
			"size":{
				"value":110,
				"random":true,//サイズをランダムに
				"anim":{
					"enable":true,
					"speed":4,
					"size_min":70,
					"sync":false
				}
			},
			"line_linked":{
				"enable":false,
			},
			"move":{
				"enable":true,
				"speed":7,//この数値を小さくするとゆっくりな動きになる
				"direction":"bottom",//右下に向かって落ちる
				"random":false,//動きはランダムにしない
				"straight":false,//動きをとどめない
				"out_mode":"out",//画面の外に出るように描写
				"bounce":false,//跳ね返りなし
				"attract":{
					"enable":false,
					"rotateX":281.9177489524316,
					"rotateY":127.670995809726
				}
			}
		},
		"interactivity":{
			"detect_on":"canvas",
			"events":{
				"onhover":{
					"enable":false,
				},
				"onclick":{
					"enable":false,
				},
				"resize":true
			}
		},
		"retina_detect":true,
		"resize":true
	});
}

function switchByWidth(){
    if (window.matchMedia('(max-width: 623px)').matches) {
        document.getElementById('sentence').innerHTML = 
		'<p>リアルにパチンコで生計を立てている</br>割とマジですごい人。</p><p>その他会社も経営しているやり手の</br>ギャンブル系Vtuber。</p><p>言いたい事はハッキリ言うため</br>口が悪かったりするが、</br>基本筋が通っているため悪い印象は</br>受けない。</p><p>因みにエジプトのスフィンクスは</br>別に好きではない。</p>'
    } else {
		document.getElementById('sentence').innerHTML = 
		'<p>リアルにパチンコで生計を立てている割とマジですごい人。</p><p>その他会社も経営しているやり手のギャンブル系Vtuber。</p><p>言いたい事はハッキリ言うため口が悪かったりするが、</br>基本筋が通っているため悪い印象は受けない。</p><p>因みにエジプトのスフィンクスは別に好きではない。</p>'
	}
}

window.onload = switchByWidth;
window.onresize = switchByWidth;